databases:
  - name: postgres
    ipAllowList: []
    # databaseName: mysite
    # user: mysite

services:
  - type: web
    name: rails
    env: ruby
    # runtime: ruby
    buildCommand: "./bin/render-build.sh"
    # startCommand: "bundle exec puma -C config/puma.rb"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
